baseurl = "./"
languageCode = "en-us"
title = "Viemacs Notes"
theme = "ev"

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
# The monokai stylesheet is included in the base template.
pygmentsUseClasses = true

defaultContentLanguage = "en"

[params]
search = true
  
# Configure the language example tabs.
[[params.language_tabs]]
key = "go"
name = "Go" 
[[params.language_tabs]]
key = "c++"
name = "C" 
[[params.language_tabs]]
key = "shell"
name = "Shell" 
[[params.language_tabs]]
key = "python"
name = "Python"
[[params.language_tabs]]
key = "javascript"
name = "Javascript"
[[params.language_tabs]]
key = "sql"
name = "SQL"

# #Languages 
# [languages]

# [languages.en]
# languageName = "English"
# weight = 2
# title = "DocuAPI Example Site"

# # Left sidebar footer items. Use HTMl or Markdown.
# toc_footers = [ 
# "<a href='#'>Sign Up for a Developer Key</a>",
# "Documentation Powered by [DocuAPI](https://github.com/bep/docuapi)",
# "Hugo Theme by [bep](https://github.com/bep)"
# ]
# [languages.en.blackfriday]
# angledQuotes = false
# hrefTargetBlank = true
